### PR TITLE
CORI environement using defautl installation on NERSC

### PR DESCRIPTION
**Pull request by parkjm**
IPS framework, Dakota, NTCC library, and python API for PPPL Plasma States have been installed on the NERSC atom software directory:

`/global/common/software/atom/cori`

Use ips.env.cori for this installation with **python3**

### CODE REVIEW

**Comment by smithsp** [comment]
@parkjm You might request that this be made a linux module for IPS from NERSC (consult@nersc.gov ?)  Then each person just does

module load IPS

Would that be helpful?

**Comment by parkjm** [comment]
@smithsp good idea! @cianciosa also had similar idea. 

How about omit on CORI?

**Comment by orso82** [comment]
@parkjm this is how we run OMFIT on cori
https://omfit.io/installations/NERSC.html
but indeed we could move it under /global/common/software/atom/cori
and create a linux module for it.

Do you know how does it work for users permissions?

**Comment by parkjm** [comment]
@orso82 Does omfit use a linux module from NERSC already? It seems that users need to know where the omfit module file is located. @smithsp's idea looks cool as we do `module load omfit` on IRIS. 

The permission for /global/common/software/atom is same to the atom project directory, only people in the atom group can access. We may give "others" read-permission, so that anyone can use the atom product. Thought?

**Comment by smithsp** [comment]
@parkjm raises a good point about giving the permission to load a module, but not permission to run a code.  They should be tied together.

**Pull request merged**
